/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * Access information about episodes from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Episode,
} from '../models/index';
import {
    EpisodeFromJSON,
    EpisodeToJSON,
} from '../models/index';

export interface GetEpisodesByIdRequest {
    ids: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Fetch episodes by ID
     */
    async getEpisodesByIdRaw(requestParameters: GetEpisodesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Episode>>> {
        if (requestParameters.ids === null || requestParameters.ids === undefined) {
            throw new runtime.RequiredError('ids','Required parameter requestParameters.ids was null or undefined when calling getEpisodesById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/episode/{ids}`.replace(`{${"ids"}}`, encodeURIComponent(String(requestParameters.ids))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EpisodeFromJSON));
    }

    /**
     * Fetch episodes by ID
     */
    async getEpisodesById(requestParameters: GetEpisodesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Episode>> {
        const response = await this.getEpisodesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
